module.exports = {
  images: './src/images/**/*.*',
  plugins: './src/plugins/**/*.*',
  fonts: './src/fonts/**/*.*',
  configs: './src/config/**/*.*',
  translations: './src/translations/**/*.*',
  jsMain: './src/js/app.jsx',
  jsFiles: './src/js/**/*.js',
  eventSource: './src/js/app/eventSource/**/*.*',
  jsxFiles: './src/js/**/*.jsx',
  lessMain: './src/less/app.less',
  lessFiles: './src/less/**/*.less',
  htmlMain: './src/*.html',
  htmlFiles: './src/**/*.html',
  vendor: './public/dist/js/vendor',
  bundle: 'app.js',
  buildCss: './public/dist/css',
  buildJs: './public/dist/js',
  buildHtml: './public',
  buildImages: './public/dist/images',
  buildPlugins: './public/dist/plugins',
  buildFonts: './public/dist/fonts',
  buildConfigs: './public/dist/config',
  buildTranslations: './public/dist/translations',
  build: './public/dist',
};
