"use strict";
var express_1 = require("express");
var defaultController_1 = require("../controllers/defaultController");
var userController_1 = require("../controllers/userController");
var teacherController_1 = require("../controllers/teacherController");
var studentController_1 = require("../controllers/studentController");
var authController_1 = require("../controllers/authController");
var lessonController_1 = require("../controllers/lessonController");
var categoryController_1 = require("../controllers/categoryController");
var classroomController_1 = require("../controllers/classroomController");
var router = express_1.Router();
// load modules
router.use('/user', userController_1.default);
router.use('/attendee/teacher', teacherController_1.default);
router.use('/attendee/student', studentController_1.default);
router.use('/lesson', lessonController_1.default);
router.use('/category', categoryController_1.default);
router.use('/classroom', classroomController_1.default);
router.use('/', authController_1.default);
router.use('/', defaultController_1.default);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = router;
